#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

#Adjust the firewall
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

#Configure Nginx to return "Hello World!" at the root path
echo "Hello World!" > /var/www/html/index.html

# Enable the new site
sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/hello-world

# Restart Nginx
sudo service Nginx restart
