#!/usr/bin/env bash
# Install Nginx
CONFIG_FILE="/etc/nginx/sites-available/default"
sudo apt-get update
sudo apt-get install -y nginx

#Adjust the firewall
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to listen on port 80
sudo tee "$CONFIG_FILE" <<EOF
server {
    listen 80;
    server_name http://incredibles.tech;
}
EOF

#Configure Nginx to return "Hello World!" at the root path
echo "Hello World!" > /var/www/html/index.html

# Enable the new site
sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/hello-world

# Restart Nginx
sudo service Nginx restart
