#!/usr/bin/env bash
# Install Nginx to webserver
sudo apt-get update
sudo apt-get install -y nginx
# Configure Nginx to listen to port 80
sudo ufw allow 'Nginx HTTP'

# Configure defaul Nginx server block
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name incredibles.tech;
    location / {
        try_files \$uri \$uri/ /index.html;
    }
    location /redirect_me {
	return 301 http://www.youtube.com;
    }
}
EOF

#Configure Nginx to return "Hello World!" at root path
sudo tee /var/www/html/index.html <<EOF
Hello World!
EOF

# Restart Nginx
sudo service nginx restart
