#!/usr/bin/env bash
# Install Nginx to webserver
sudo apt-get update
sudo apt-get install -y nginx
# Configure Nginx to listen to port 80
sudo ufw allow 'Nginx HTTP'

# Set the path to your custom 404 page
sudo tee /var/www/html/404.html > /dev/null <<EOF
Ceci n'est pas une page
EOF

# Configure Nginx to return "Hello World!" at root path
sudo tee /var/www/html/index.html <<EOF
Hello World!
EOF

sudo service nginx start

# Add custom response header to Nginx Configuration
sudo sed -i.bak "12i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx -t
sudo service nginx restart
