#!/usr/bin/env bash
# Install HAProxy
sudo apt update  -y
sudo apt install -y haproxy

# Configuration of Haproxy edit config file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen http-in
bind :80
balance roundrobin
server 124352-web-01 100.25.156.46:80 check
server 124352-web-02 34.232.52.141:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAProxy service
service haproxy start
