#!/usr/bin/env bash
# Resolve Nginx to listen to port 80 and turn off IPv6

sudo sysctl net.ipv6.conf.all.disable_ipv6=1
sudo sysctl net.ipv6.conf.default.disable_ipv6=1

sudo apt-get update
sudo apt-get install -y nginx
# Configure Nginx to listen to port 80
sudo sed i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo nginx -t
sudo service nginx restart
# Check Nginx status
sudo service nginx status
