#!/usr/bin/env bash
# Shorter resolve to to listen on port 80
sudo apt-get install -y nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo kill -TERM $(pgrep -f "/usr/sbin/nginx")
