#!/usr/bin/env bash
# Shorter resolve to to listen on port 80
sudo apt-get install -y nginx
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo pkill -f -TERM "/usr/sbin/nginx"
