#!/usr/bin/env bash
# Shorter resolve to to listen on port 80
sudo apt-get install -y nginx
sudo sed -i '/listen \[::\]:80 default_server;/d' /etc/nginx/sites-available/default
sudo pkill -f -TERM "/usr/sbin/nginx"
