#!/usr/bin/env bash
# This displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

Hours=0
while [ $Hours -le 12 ];
do
    echo "Hour: $Hours"
    Minutes=1
    while [ $Minutes -le 59 ]
    do
	echo "$Minutes"
	((Minutes++))
    done
    ((Hours++))
done
