#!/usr/bin/env bash
# Displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# Do not display hidden files
for f in *;
do
    if [[ ! "$f" =~ ^\. ]];
    then
	echo "${f##*-}"
    fi
done
