#!/usr/bin/env bash
# Setup ufw firewall

sudo apt-get update

#install ufw
sudo apt-get install -y ufw

# ufw Configuration
sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw enable
