#!/usr/bin/env bash
# Run software as another user
# Check if an argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get username from the argument
username="$1"

# Check if user exists using 'id' command
if id "$username" &>/dev/null; then
	# Run whoami command under the specified user using 'sudo'
	sudo -u "$username" whoami
else
	echo "User does not exist."
	exit 1
fi
