#!/usr/bin/env bash
# Run software as another user
# Check if an argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the username from the argument
username="$1"

# Check if the user exists using 'id' command
if id "$username" &>/dev/null; then
	# Run the whoami command under the specified user using 'sudo'
	su "$username" -c whoami
else
	echo "User '$username' does not exist or does not have a home directory."
	exit 1
fi
