#!/usr/bin/env bash
# Configures container to have Nginx running as nginx user

# Replace the user directive in nginx.conf with nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify the default site to listen on all active IPs on port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Change ownership and configuration mode
chmod 644 /etc/nginx/nginx.conf

pkill apache2
# Restart Nginx to apply the changes
sudo -u nginx service nginx start
