#!/usr/bin/env bash
# SSH Configuration file for the local SSH Client
Host strongestavenger@strongestavenger
IdentityFile ~/.ssh/school
PasswordAuthentication no
RSAAuthentication yes
PubkeyAuthentication yes
